### ISSUE TITLE
Function export creates invalid YAML

### ISSUE THREAD

**Issue by pavius** [iguazio/dashboard-controls#89]
See below:

1. Memory and CPU are not valid values
2. Env encoded improperly
3. Labels and annotations missing completely (they were part of the function)
4. noPullBaseImages set to "true" - should not be set

```
metadata:
    name: exp
spec:
    description: Short
    handler: 'main:Handler'
    runtime: golang
    resources:
        limits:
            memory: '2147483648'
            cpu: '17'
    image: 'nuclio/processor-exp:latest'
    triggers:
        h:
            class: ""
            kind: http
            maxWorkers: 8
            attributes:
                ingresses: {}
                port: 40000
    build:
        path: /tmp/nuclio-build-013410311/source/main.go
        functionSourceCode: LyoKQ29weXJpZ2h0IDIwMTcgVGhlIE51Y2xpbyBBdXRob3JzLgoKTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbnNlLCBWZXJzaW9uIDIuMCAodGhlICJMaWNlbnNlIik7CnlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS4KWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CgogICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCgpVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCmRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCldJVEhPVVQgV0FSUkFOVElFUyBPUiBDT05ESVRJT05TIE9GIEFOWSBLSU5ELCBlaXRoZXIgZXhwcmVzcyBvciBpbXBsaWVkLgpTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCmxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgoqLwoKLy8KLy8gTGlzdGVucyB0byBhIFJhYmJpdE1RIHF1ZXVlIGFuZCByZWNvcmRzIGFueSBtZXNzYWdlcyBwb3N0ZWQgdG8gYSBnaXZlbiBxdWV1ZS4KLy8gQ2FuIHJldHJpZXZlIHRoZXNlIHJlY29yZGVkIG1lc3NhZ2VzIHRocm91Z2ggSFRUUCBHRVQsIGRlbW9uc3RyYXRpbmcgaG93IGEgc2luZ2xlCi8vIGZ1bmN0aW9uIGNhbiBiZSBpbnZva2VkIGZyb20gZGlmZmVyZW50IHRyaWdnZXJzLgovLwoKcGFja2FnZSBtYWluCgppbXBvcnQgKAoJImlvL2lvdXRpbCIKCSJuZXQvaHR0cCIKCSJvcyIKCgkiZ2l0aHViLmNvbS9udWNsaW8vbnVjbGlvLXNkay1nbyIKKQoKY29uc3QgZXZlbnRMb2dGaWxlUGF0aCA9ICIvdG1wL2V2ZW50cy5qc29uIgoKZnVuYyBIYW5kbGVyKGNvbnRleHQgKm51Y2xpby5Db250ZXh0LCBldmVudCBudWNsaW8uRXZlbnQpIChpbnRlcmZhY2V7fSwgZXJyb3IpIHsKCWNvbnRleHQuTG9nZ2VyLkluZm9XaXRoKCJSZWNlaXZlZCBldmVudCIsICJib2R5Iiwgc3RyaW5nKGV2ZW50LkdldEJvZHkoKSkpCgoJLy8gaWYgd2UgZ290IHRoZSBldmVudCBmcm9tIHJhYmJpdAoJaWYgZXZlbnQuR2V0VHJpZ2dlckluZm8oKS5HZXRDbGFzcygpID09ICJhc3luYyIgJiYgZXZlbnQuR2V0VHJpZ2dlckluZm8oKS5HZXRLaW5kKCkgPT0gInJhYmJpdE1xIiB7CgoJCWV2ZW50TG9nRmlsZSwgZXJyIDo9IG9zLk9wZW5GaWxlKGV2ZW50TG9nRmlsZVBhdGgsIG9zLk9fQ1JFQVRFfG9zLk9fQVBQRU5EfG9zLk9fV1JPTkxZLCAwNjAwKQoJCWlmIGVyciAhPSBuaWwgewoJCQlyZXR1cm4gbmlsLCBlcnIKCQl9CgoJCWRlZmVyIGV2ZW50TG9nRmlsZS5DbG9zZSgpCgoJCS8vIHdyaXRlIHRoZSBib2R5IGZvbGxvd2VkIGJ5ICcsICcKCQlmb3IgXywgZGF0YVRvV3JpdGUgOj0gcmFuZ2UgW11bXWJ5dGV7CgkJCWV2ZW50LkdldEJvZHkoKSwKCQkJW11ieXRlKCIsICIpLAoJCX0gewoKCQkJLy8gd3JpdGUgdGhlIHRoaW5nIHRvIHdyaXRlCgkJCWlmIF8sIGVyciA9IGV2ZW50TG9nRmlsZS5Xcml0ZShkYXRhVG9Xcml0ZSk7IGVyciAhPSBuaWwgewoJCQkJcmV0dXJuIG5pbCwgZXJyCgkJCX0KCQl9CgoJCS8vIGFsbCdzIHdlbGwKCQlyZXR1cm4gbmlsLCBuaWwKCX0KCgkvLyBvcGVuIHRoZSBsb2cgZm9yIHJlYWQKCWV2ZW50TG9nRmlsZSwgZXJyIDo9IG9zLk9wZW5GaWxlKGV2ZW50TG9nRmlsZVBhdGgsIG9zLk9fUkRPTkxZLCAwNjAwKQoJaWYgZXJyICE9IG5pbCB7CgkJcmV0dXJuIG5pbCwgZXJyCgl9CgoJZGVmZXIgZXZlbnRMb2dGaWxlLkNsb3NlKCkKCgkvLyByZWFkIHRoZSBlbnRpcmUgZmlsZQoJZXZlbnRMb2dGaWxlQ29udGVudHMsIGVyciA6PSBpb3V0aWwuUmVhZEFsbChldmVudExvZ0ZpbGUpCglpZiBlcnIgIT0gbmlsIHsKCQlyZXR1cm4gbmlsLCBlcnIKCX0KCgkvLyBjaG9wIG9mZiB0aGUgbGFzdCAyIGNoYXJzIGFuZCBlbmNsb3NlIGluIGEgWyBdCglldmVudExvZ0ZpbGVDb250ZW50c1N0cmluZyA6PSAiWyIgKyBzdHJpbmcoZXZlbnRMb2dGaWxlQ29udGVudHNbOmxlbihldmVudExvZ0ZpbGVDb250ZW50cyktMl0pICsgIl0iCgoJLy8gcmV0dXJuIHRoZSBjb250ZW50cyBhcyBKU09OCglyZXR1cm4gbnVjbGlvLlJlc3BvbnNlewoJCVN0YXR1c0NvZGU6ICBodHRwLlN0YXR1c09LLAoJCUNvbnRlbnRUeXBlOiAiYXBwbGljYXRpb24vanNvbiIsCgkJQm9keTogICAgICAgIFtdYnl0ZShldmVudExvZ0ZpbGVDb250ZW50c1N0cmluZyksCgl9LCBuaWwKfQo=
        noBaseImagesPull: true
        commands:
            - ls
    platform: {}
    targetCPU: 45
    minReplicas: 3
    maxReplicas: 3
    env:
        -
            name: e1
            value: ev1
            $$hashKey: 'object:2999'
        -
            name: e2
            value: ev2
            $$hashKey: 'object:3017'
```
